/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ----- Public site -----
        navy: "#1A2E4A",
        "navy-deep": "#0F1F35",
        gold: "#B8973A",
        "gold-soft": "#D4B968",
        cream: "#FDF8F2",
        surface: "#F9F7F3",
        charcoal: "#2A2A2A",
        muted: "#6B6B6B",
        line: "#E5E0D8",
        "line-dark": "#2B3A52",

        // ----- Admin console (MD3-flavoured tokens) -----
        "deep-navy": "#1A2E4A",
        primary: "#021934",
        "primary-container": "#1A2E4A",
        "primary-fixed": "#d5e3ff",
        "primary-fixed-dim": "#b4c7eb",
        "on-primary": "#ffffff",
        "on-primary-container": "#8296b7",
        "on-primary-fixed": "#051c37",
        "on-primary-fixed-variant": "#344765",
        "warm-gold": "#B8973A",
        secondary: "#755b00",
        "secondary-fixed": "#ffdf91",
        "secondary-fixed-dim": "#e7c361",
        "on-secondary-fixed": "#241a00",
        "on-secondary-fixed-variant": "#594400",
        "charcoal-text": "#333333",
        background: "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        outline: "#74777e",
        "outline-variant": "#c4c6ce",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#44474d",
        "on-background": "#1a1c1c",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        serif: ['"Playfair Display"', "serif"],
        sans: ["Inter", "sans-serif"],
        mono: ['"JetBrains Mono"', "monospace"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", fontWeight: "500" }],
        "headline-lg": ["36px", { lineHeight: "44px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "30px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "cta-label": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.15em", fontWeight: "600" },
        ],
      },
      letterSpacing: {
        widest: "0.25em",
      },
    },
  },
  plugins: [],
}
